schema_version = 3

[project]
uuid = "28a57c53-0510-4bfd-adff-11f4d50508db"
name = "planledger"


[ledgers.releaseledger.mounts.data]
storage = "project"

[ledgers.releaseledger.mounts.indexes]
storage = "cache"
