schema_version = 2

[project]
uuid = "28a57c53-0510-4bfd-adff-11f4d50508db"
name = "planledger"

[storage.workspace]
default_provider = "user-data"
namespace = "ledgerwerk"

[storage.cache]
default_provider = "user-cache"
namespace = "ledgerwerk"

[ledgers.taskledger.config]
location = "project"
path = "task/config.toml"

[ledgers.taskledger.mounts.data]
storage = "workspace"
path = "task/taskledger/28a57c53-0510-4bfd-adff-11f4d50508db"
scope = "project"

[ledgers.taskledger.mounts.indexes]
storage = "cache"
scope = "checkout"
path = "task/taskledger-indexes"

[ledgers.planledger.config]
location = "project"
path = "plan/config.toml"

[ledgers.planledger.mounts.data]
storage = "workspace"
scope = "project"
path = "plan/planledger/28a57c53-0510-4bfd-adff-11f4d50508db"
